setwd('C:\\Users\\Austin\\Desktop\\Virginia Tech\\CS 3654\\CMDA\\FINAL PROJECT')
fbcleanr = read.table('fbclean.csv', sep=',', header=T)
attach(fbcleanr)
model <- lm(Winning.Percentage ~ YDSG + YDSAG + NETPUNT + PUNTRETAVG, data = fbcleanr)
summary(model)
exp(model$coef)
model2 <- lm(Winning.Percentage ~ P.YDSG + R.YDSG + YDSAG + NETPUNT + PUNTRETAVG)
summary(model2)
exp(model2$coef)
